name: Compile and Upload LaTeX PDF

on:
  push:
    branches:
      - main

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v3

    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex

    - name: Upload PDF file as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: PDF
        path: main.pdf

    - name: Get number of commits
      id: get_commits
      run: echo "COMMIT_COUNT=$(git rev-list --count HEAD)" >> $GITHUB_ENV

    - name: Create Release
      uses: softprops/action-gh-release@v0.1.15
      with:
        tag_name: "release-${{ env.COMMIT_COUNT }}"
        files: main.pdf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
